---
- hosts: checkboxio  
  become: yes
  become_user: root
  vars: 
    git_repo: 'https://github.ncsu.edu/akpatil/CSC519-Project.git'
    project_path: '/home/vagrant'
    deploy_user: vagrant
    dependencies: 
          - 'git'
          - 'nodejs-legacy'
          - 'npm'
          - 'mongodb'
          - 'python-pip'
          - 'nginx'

  vars_prompt:
    - name: "emailid"
      private: no
      prompt: "Please enter your email-id"
    - name: "password"
      private: yes
      prompt: "PLease enter your password"

  tasks:   
    - name: apt update
      become_user: root
      command: sudo apt-get update
        
    - name: Install dependencies
      apt: name={{ item }} state=present
      with_items: "{{ dependencies }}"

    - name: Install the latest pymongo package
      pip: name=pymongo state=latest use_mirrors=no
      
    - name: Clone submission repository
      git: repo=https://{{lookup('env','GITUSER')}}:{{ lookup('env', 'GITPWD' )}}@github.ncsu.edu/akpatil/CSC519-Project.git dest=checkboxio/.

    - name: Set email in environment variable
      command: chdir=CSC519-Project/checkbox.io/server-side/site export SMTPEMAIL={{ emailid }}
      
    - name: Set password in environment variable
      command: chdir=CSC519-Project/checkbox.io/server-side/site export SMTPPWD={{ password }}

    - name: Create user
      mongodb_user:
        database: admin
        name: admin
        password: admin
        state: present

    - name: Copy nginx config file
      become: yes
      template:
        src: templates/nginx.conf
        dest: /etc/nginx/sites-enabled 

    - name: Removing default config file
      command: "rm {{ item }}"
      with_items: 
        - /etc/nginx/sites-available/default
        - /etc/nginx/sites-enabled/default

    - name: Starting NGINX
      service:
        name: nginx
        state: started

    - name: npm install
      command: chdir=CSC519-Project/checkbox.io/server-side/site npm install

    - name: Run checkbox.io
      command: chdir=CSC519-Project/checkbox.io/server-side/site node server.js

