---
- hosts: checkboxio  
  become: yes
  become_user: root
  vars: 
    git_repo: 'https://github.ncsu.edu/akpatil/CSC519-Project.git'
    project_path: '/home/vagrant'
    deploy_user: vagrant
    dependencies: 
          - 'git'
          - 'nodejs-legacy'
          - 'npm'
          - 'mongodb'
          - 'python-pip'
          - 'nginx'

  tasks:   
    - name: apt update
      become_user: root
      command: sudo apt-get update

    - name: Install dependencies
      apt: name={{ item }} state=present
      with_items: "{{ dependencies }}"

    - name: Clone submission repository
      git: repo=https://{{lookup('env','GITUSER')}}:{{ lookup('env','GITPWD')}}@github.ncsu.edu/akpatil/CSC519-Project.git dest=checkboxio/.

    - name: Install the latest pymongo package
      pip: name=pymongo state=latest use_mirrors=no

    - name: Create user
      mongodb_user:
        database: admin
        name: admin
        password: admin
        state: present

    - name: Copy nginx config file
      become: yes
      command: cp checkboxio/M1/nodejsProject/checkbox.io/local-conf/nginx.conf /etc/nginx/nginx.conf

    - name: Copy nginx default file
      become: yes
      command: cp checkboxio/M1/nodejsProject/checkbox.io/local-conf/default /etc/nginx/sites-enabled/default

    - name: Starting NGINX
      service:
        name: nginx
        state: restarted

     - name: npm install
       command: chdir=checkboxio/M1/nodejsProject/checkbox.io/server-side/site npm install

    - name: Run checkbox.io
      command: chdir=checkboxio/M1/nodejsProject/checkbox.io/server-side/site node server.js



